programs:
  sleep:
    cmd: "sleep 5"
    numprocs: 2
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
      - 1
    starttime: 1
    startretries: 3
    stopsignal: SIGTERM
    stoptime: 5
    stdout: /dev/stdout
    stderr: /dev/stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42
    workingdir: /workspaces/taskmaster
    umask: 022
  sleep2:
    cmd: "sleep 20"
    numprocs: 2
    autostart: true
    autorestart: always
    exitcodes:
      - 0
      - 2
    starttime: 2
    startretries: 3
    stopsignal: SIGTERM
    stoptime: 1
  env:
    cmd: env
    numprocs: 1
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
      - 1
    starttime: 0
    startretries: 3
    stopsignal: SIGTERM
    stoptime: 10
    stdout: /dev/stdout
    env:
      42STARTED_BY: taskmaster
      42ANSWER: 42
      42FOO: bar
    workingdir: /workspaces/taskmaster
    umask: 022
