programs:
  sleep:
    cmd: "sleep 100"
    numprocs: 5
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
      - 2
    starttime: 5
    startretries: 3
    stopsignal: SIGTERM
    stoptime: 10
    stdout: /dev/stdout
    stderr: /dev/stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42
    workingdir: /workspaces/taskmaster
    umask: 022
  sleep2:
    cmd: "sleep 100"
    numprocs: 5
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
      - 2
    starttime: 5
    startretries: 3
    stopsignal: SIGTERM
    stoptime: 10

