programs:
  sleep: #autorestart but no startretries
    cmd: "sleep 100"
    numprocs: 1
    autostart: true
    autorestart: always
    exitcodes:
      - 0
      - 2
    starttime: 2
    startretries: 3
    stopsignal: sigusr1
    stdout: /dev/stdout
    stderr: /dev/stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42
    workingdir: /workspaces/taskmaster
    umask: 022
  sleep2: # no cmd
    cmd: "sleep 20"
    numprocs: 2
    autostart: true
    autorestart: never
    exitcodes:
      - 0
      - 2
    starttime: 2
    startretries: 3
    stopsignal: SIGTERM
    stoptime: 1
  env:
    cmd: "bash -c 'env | grep 42'"
    numprocs: 1
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
      - 1
    starttime: 0
    startretries: 3
    stopsignal: SIGTERM
    stoptime: 10
    stdout: jamoncito
    env:
      42STARTED_BY: taskmaster
      42ANSWER: 42
      42FOO: bar
    workingdir: /workspaces/taskmaster
    umask: 022
